repos:
  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy -p ../../build --extra-arg=-w
        language: system
        files: \.(c|cc|cxx|cpp)$
        exclude: ^soem_rsl/soem_rsl/(?:osal/(?!linux/)|oshw/(?!linux/)|test/(?!linux/(?:eepromtool|simple_test|slaveinfo)/))
